[project]
name = "colabradoodle"
version = "0.1.0"
description = "Colabradoodle - A collaborative AI experiment"
requires-python = ">=3.8"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_fixture_loop_scope = "function"
pythonpath = ["."]
testpaths = ["tests"]